package com.yoinami.sarr_mal_api.controller;

import org.springframework.web.bind.annotation.*;


@RestController
@RequestMapping("/food")
public class FoodController {
    /*
     * We will call Food Generated By AI "Recommended Food", Food confirmed by User will be "Meal Plan"
     * Recommended Food --confirm--> MealPlan --eaten--> FoodHistory
     * */

    //Get recommended food
    @GetMapping("/getRecommededFood")
    public String getRecommendFood() {
        return "getRecommededFood";
    }

    //Generate new recommended food from AI
    @GetMapping("/generateRecommendedFood")
    public String generateRecommendedFood() {
        return "generateRecommendedFood";
    }

    @PutMapping("/confrimRecommendedFood")
    public String confrimRecommendedFood() {
        return "confrimRecommendedFood";
    }

    @GetMapping("/getMealPlan")
    public String getMealPlan() {
        return "getMealPlan";
    }

    @GetMapping("/getMealPlanById")
    public String getMealPlanById(@RequestParam("id") Long id) {
        return "getMealPlanById";
    }

    @PutMapping("/tickMealPlan")
    public String tickMealPlan(@RequestParam("id") Long id) {
        return "tickMealPlan";
    }

    @GetMapping("/getFoodHistory")
    public String getFoodHistory() {
        return "getFoodHistory";
    }

    @GetMapping("/getFoodDetail")
    public String getFoodDetail(@RequestParam("id") Long id) {
        return "getFoodDetail";
    }
}
