package com.yoinami.sarr_mal_api.controller;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.yoinami.sarr_mal_api.payload.GeminiJsonResponse;
import org.springframework.web.bind.annotation.*;


@RestController
@RequestMapping("/food")
public class FoodController {
    private final ControllerHelper controllerHelper;

    public FoodController(ControllerHelper controllerHelper) {
        this.controllerHelper = controllerHelper;
    }
    /*
     * We will call Food Generated By AI "Recommended Food", Food confirmed by User will be "Meal Plan"
     * Recommended Food --confirm--> MealPlan --eaten--> FoodHistory
     * */

    //Get recommended food
    @GetMapping("/getRecommededFood")
    public String getRecommendFood() {
        String respond = null;
        try {
            GeminiJsonResponse res = controllerHelper.generateRecommendedFoodFromGemini();
            respond = "\nBreakfast-main" + res.getResponse().getBreakfast().getMainDish().toString();
            respond += "\nBreakfast-side" + res.getResponse().getBreakfast().getSideDish().toString();
            respond += "\nLunch-main" + res.getResponse().getLunch().getMainDish().toString();
            respond += "\nLunch-side" + res.getResponse().getLunch().getSideDish().toString();
            respond += "\nDinner-main" + res.getResponse().getDinner().getMainDish().toString();
            respond += "\nDinner-side" + res.getResponse().getDinner().getSideDish().toString();
        } catch (JsonProcessingException e) {
            return e.getMessage();
        } finally {

        }
        return respond;
    }

    //Generate new recommended food from AI
    @GetMapping("/generateRecommendedFood")
    public String generateRecommendedFood() {
        return "generateRecommendedFood";
    }

    @PutMapping("/confrimRecommendedFood")
    public String confrimRecommendedFood() {
        return "confrimRecommendedFood";
    }

    @GetMapping("/getMealPlan")
    public String getMealPlan() {
        return "getMealPlan";
    }

    @GetMapping("/getMealPlanById")
    public String getMealPlanById(@RequestParam("id") Long id) {
        return "getMealPlanById";
    }

    @PutMapping("/tickMealPlan")
    public String tickMealPlan(@RequestParam("id") Long id) {
        return "tickMealPlan";
    }

    @GetMapping("/getFoodHistory")
    public String getFoodHistory() {
        return "getFoodHistory";
    }

    @GetMapping("/getFoodDetail")
    public String getFoodDetail(@RequestParam("id") Long id) {
        return "getFoodDetail";
    }
}
